# ------------ DEPRECATED ------------
#
# This has been deprecated. DO NOT
#   USE IT!
#
# ------------ DEPRECATED ------------

# syntax=docker/dockerfile:1
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Pacific/Los_Angeles
ENV LC_ALL=C

COPY start-web.sh /start-web.sh

RUN chmod a+rx /start-web.sh && \
    apt-get update && \
    apt-get --no-install-recommends -y upgrade && \
    apt-get --no-install-recommends -y install \
    bash sudo curl xsel

SHELL [ "/bin/bash", "-c" ]

RUN apt-get update && \
    apt-get --no-install-recommends -y upgrade && \
    apt-get -y install npm && \
    npm install --global n && \
    n 17

RUN npm install --global serve && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ADD web /web

EXPOSE 3000

CMD [ "/bin/bash", "/start-web.sh" ]